image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev &&
      pip install docker-compose
  - docker info
  - docker version
  - docker-compose version

stages:
  - test
  - build

compose-test:
  stage: test
  script:
    - docker-compose config
  tags:
    - docker

compose-build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker
