image: docker:latest

cache:
  untracked: true

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev python3 bash git &&
      pip install docker-compose &&
      pip3 install PyYAML
  - docker info
  - docker version
  - docker-compose version
  - ls -al

stages:
  - run-tests

#compose-test:
#  stage: test
#  script:
#    - docker-compose config
#  tags:
#    - docker
#
#compose-build:
#  stage: build
#  script:
#    - docker-compose build
#    - docker-compose up -d
#    - docker-compose ps bitcoind
#    - docker-compose ps ipfs
#    - docker-compose ps postgres
#    - docker-compose ps scraper
#    - docker exec -i svstdocker_bitcoind_1 /usr/local/bin/bitcoin-cli generate 104
#    - docker exec -i svstdocker_bitcoind_1 /usr/local/bin/bitcoin-cli getbalance
#    - docker-compose up producer
#  tags:
#    - docker

compose-run-tests:
  stage: run-tests
  script:
    - env
    - ./_git_clone_all.sh && ls && ./_reset_tests.sh && ./_run_test.sh
  tags:
    - docker
