version: '2.1'

services:
  bitcoind:
    build:
      context: ./docker-bitcoind/
    entrypoint: "sh -c 'btc_init && bitcoind -regtest'"
    environment:
      - DISABLEWALLET=0
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=YwdRRcTVR7auH0xWukWUd5qk77t2rxP6FKJlk1YL0YIM
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18333:18333"
    volumes:
      - ./bitcoind-data:/bitcoin

  ipfs:
    depends_on:
      - "bitcoind"
    image: "jbenet/go-ipfs"
    ports:
      - "127.0.0.1:5001:5001"
      - "4001:4001"
    volumes:
      - ./ipfs-data:/ipfs-data

  postgres:
    depends_on:
      - "ipfs"
    image: "postgres:9.6"
    environment:
      - PGDATA=/postgres-data
    volumes:
      - ./postgres-data:/postgres-data
    expose:
      - "5678"

  scraper:  # haskell
    depends_on:
      - "postgres"
    build:
      context: ./dockerfiles/scraper/
      dockerfile: Dockerfile
    entrypoint: "scraper"

  producer:  # haskell
    depends_on:
      - "postgres"
    build:
      context: ./dockerfiles/producer/
      dockerfile: Dockerfile
    entrypoint: "pallet-gen 10"

  stress-test-pallet-verification:  # C
    depends_on:
      - "postgres"
    build:
      context: ./dockerfiles/stress-test-pallet-verification/
      dockerfile: Dockerfile
    entrypoint: "stress-test-pallet-verification/src/perf"

  # header-download:  # python
  #   depends_on:
  #     - "postgres"
  #   build:
  #     context: ./svst-python
  #     dockerfile: Header-Download-Dockerfile
  #     args:
  #       pubkey: ""

  # pallet-download:  # python
  #   depends_on:
  #     - "bitcoind"
  #   build:
  #     context: ./svst-python
  #     dockerfile: Pallet-Download-Dockerfile

  # pallet-verifier:  # haskell
  #   depends_on:
  #     - "postgres"
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: Pallet-Verifier-Dockerfile

  # state-maker:  # python
  #   depends_on:
  #     - "postgres"
  #   build:
  #     context: ./svst-python
  #     dockerfile: Statemaker-Dockerfile

  # vote-explorer:  # python
  #   depends_on:
  #     - "statemaker"
  #   build:
  #     context: ./svst-python
  #     dockerfile: VoteExplorer-Dockerfile
  #   ports:
  #     - "8080:80"

