FROM exo1/dev-base-haskell:latest

# Add stuff after this so we have a common image

ADD ./stress-test-pallet-verification /src/stress-test-pallet-verification
ADD ./svst-haskell /src/svst-haskell
ADD ./svst-python /src/svst-python
WORKDIR /src/svst-haskell

RUN stack build
RUN stack install && mv ~/.local/bin/* /usr/bin/

WORKDIR /src/stress-test-pallet-verification/src
RUN make && ./test && cp verify-pallet /usr/bin/

WORKDIR /src/svst-python


