FROM exo1/dev-base-haskell:latest

# Add stuff after this so we have a common image

ADD ./svst-haskell /src/svst-haskell
WORKDIR /src/svst-haskell

RUN stack build
RUN stack install && mv ~/.local/bin/* /usr/bin/
