FROM exo1/dev-base-python:latest

# Add stuff after this so we have a common image

ADD ./svst-haskell /src/svst-haskell
ADD ./svst-python /src/svst-python

WORKDIR /src/svst-haskell

RUN stack build
RUN stack install && mv ~/.local/bin/* /usr/bin/

WORKDIR /src/svst-python

RUN pip3 install -r requirements.txt
