# When adding things that need to be changed for testing, remember
# to update bin/2_modify_docker_test.py
#
# e.g. running bitcoind in regtest mode
#      or adding environment variables

version: '2.1'

services:
  bitcoind:
    build:
      context: ./docker-bitcoind/
    entrypoint: "sh -c 'btc_init && bitcoind'"
    env_file:
      - env_vars.env
    volumes:
      - ./bitcoind-data:/bitcoin
    expose:
      - "8332"

  ipfs:
    depends_on:
      - "bitcoind"
    image: "jbenet/go-ipfs"
    ports:
      - "4001:4001"
    volumes:
      - ./ipfs-data:/ipfs-data

  postgres:
    depends_on:
      - "ipfs"
    build:
      context: './dockerfiles/postgres/'
    env_file:
      - env_vars.env
    volumes:
      - ./postgres-data:/postgres-data

  scraper:  # haskell
    depends_on:
      - "postgres"
    build:
      context: ./dockerfiles/scraper/
      dockerfile: Dockerfile
    entrypoint: "scraper"

  producer:  # haskell & python
    depends_on:
      - "scraper"
    build:
      context: ./dockerfiles/producer/
      dockerfile: Dockerfile
    entrypoint: "sh -c './producer-production.sh'"
    env_file:
      - env_vars.env
    environment:
      - VERIFY_SECRET_KEY
      - VERIFY_PUBKEY

  header-download:  # python
    depends_on:
      - "scraper"
    build:
      context: ./dockerfiles/header-download/
      dockerfile: Dockerfile
    env_file:
      - env_vars.env

  pallet-download:  # python
    depends_on:
      - "scraper"
    build:
      context: ./dockerfiles/pallet-download/
      dockerfile: Dockerfile

  pallet-verifier:  # haskell
    depends_on:
      - "scraper"
    build:
      context: ./dockerfiles/pallet-verifier/
      dockerfile: Dockerfile

  state-maker:  # python
    depends_on:
      - "scraper"
    build:
      context: ./dockerfiles/state-maker/
      dockerfile: Dockerfile

  vote-explorer:  # python
    depends_on:
      - "state-maker"
    build:
      context: ./dockerfiles/vote-explorer/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8683:80"
