FROM exo1/dev-base-haskell:latest

# Add stuff after this so we have a common image

WORKDIR /src/svst-haskell

#RUN git pull
#RUN stack build
#RUN stack install && mv ~/.local/bin/* /usr/bin/

#WORKDIR /src

#RUN git clone https://gitlab.com/exo-one/stress-test-pallet-verification \
#    && cd stress-test-pallet-verification/src \
#    && make && ./test && cp verify-pallet /usr/bin/


